### ISSUE TITLE
Module fails tests with Math::BigFloat >= 1.999718

### ISSUE THREAD

**Issue by ribasushi** [drzigman/DBIx-Class-InflateColumn-Math-Currency#1] opened 2016-06-09 21:21 UTC
I am pretty sure this is a newly introduced bug in Math::BigFloat, but reporting it your direction as I have not investigated in depth, apart from mechanical bisecting.

Up to and including Math::BigFloat 1.999717 everything is fine. Once we jump to ...718 we get the inscrutable:

```
t/01-inflate_math_currency.t ..     
    #   Failed test 'Check Value'
    #   at t/01-inflate_math_currency.t line 18.
    #          got: 1.23
    #     expected: 1.23
    # Looks like you failed 1 test of 2.
t/01-inflate_math_currency.t .. 1/? 
#   Failed test 'Inflate Positive Math::Currency Value'
#   at t/01-inflate_math_currency.t line 19.

    #   Failed test 'Check Value'
    #   at t/01-inflate_math_currency.t line 26.
    #          got: 42
    #     expected: 42
    # Looks like you failed 1 test of 2.

#   Failed test 'Inflate Positive Integer Value'
#   at t/01-inflate_math_currency.t line 27.

    #   Failed test 'Check Value'
    #   at t/01-inflate_math_currency.t line 34.
    #          got: 1.23
    #     expected: 1.23
    # Looks like you failed 1 test of 2.
```

... and so on

This may or may not be related [to this change](https://metacpan.org/source/PJACKLAM/Math-BigInt-1.999718/CHANGES#L1710-1712).

Hope this helps

**Comment by drzigman** [comment] 2016-06-10 00:05
Greetings,

I've noticed this myself as well (ran into it when working with Math::Currency).  It does seem that something regarding the overloading of comparision operators is responsible.

I plan to look into Math::BigInt/Math::BigFloat in the next few days and I'll go ahead and submit a formal bug report (and hopefully a patch) once we see what the issue is.

Thank you for pinging me about it!  I appreciate the heads up.

I'm going to keep this issue open till we get this figured out.

**Comment by drzigman** [comment] 2016-06-10 18:53
Greetings,

I've gone ahead and filed a bug report, failing test, and patch to Math::Currency.

https://rt.cpan.org/Ticket/Display.html?id=115247

I did dig into Math::BigInt/Math::BigFloat but the changes made between v1.999717 and v1.999718 are fairly extensive.  As you suspected the relevant change was:

2016-04-22 v1.999718 pjacklam
- Add overloading of '==', '!=', '<', '<=', '>', to to Math::BigInt and
  Math::BigFloat and fix the broken overloading of '>='. These overloaded
  operators now behave like the equivalent core Perl operators.

The root of the issue is that Math::Currency implements it's own bcmp method that does not play nicely with the changes to the operator overloading made in Math::BigInt/Math::BigFloat.

Hopefully the Math::Currency maintainer John Peacock is able to take a look and do the needful shortly.

Until then, I'm going to keep this open as a reminder to myself to follow up if needed.

**Comment by drzigman** [comment] 2016-06-16 17:17
Greetings,

Huzzahs are in order!  Math::Currency v0.48 has been released to cpan specifically to address this issue and it also now includes a regression test to catch if the ==, <=, or >= breaks again.

With that update I'm closing this issue.  Thank you again for your vigilance.

**Closed as completed by drzigman** 2016-06-16 17:17 UTC
